CSC 360 A2 Instructions
================
Braden Baker
March 22, 2019

This assignment is to produce a model of median household income using
other variables in the countyComplete dataframe, which is in the
openintro package.

## Load the required libraries.

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------------------------------------------------------------ tidyverse 1.3.0 --

    ## <U+2713> ggplot2 3.2.1     <U+2713> purrr   0.3.3
    ## <U+2713> tibble  2.1.3     <U+2713> dplyr   0.8.3
    ## <U+2713> tidyr   1.0.0     <U+2713> stringr 1.4.0
    ## <U+2713> readr   1.3.1     <U+2713> forcats 0.4.0

    ## -- Conflicts --------------------------------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(openintro)
```

    ## Please visit openintro.org for free statistics materials

    ## 
    ## Attaching package: 'openintro'

    ## The following object is masked from 'package:ggplot2':
    ## 
    ##     diamonds

    ## The following objects are masked from 'package:datasets':
    ## 
    ##     cars, trees

## Problem 1

Run the commands glimpse() and summary() on the dataframe to understand
the meaning of the variables and to verify the integrity of the data.
The documentation in the openintro package is useful for understanding
the variables.

``` r
# Place your code here.
glimpse(countyComplete)
```

    ## Observations: 3,143
    ## Variables: 53
    ## $ state                                     <fct> Alabama, Alabama, Alabama, …
    ## $ name                                      <fct> Autauga County, Baldwin Cou…
    ## $ FIPS                                      <dbl> 1001, 1003, 1005, 1007, 100…
    ## $ pop2010                                   <dbl> 54571, 182265, 27457, 22915…
    ## $ pop2000                                   <dbl> 43671, 140415, 29038, 20826…
    ## $ age_under_5                               <dbl> 6.6, 6.1, 6.2, 6.0, 6.3, 6.…
    ## $ age_under_18                              <dbl> 26.8, 23.0, 21.9, 22.7, 24.…
    ## $ age_over_65                               <dbl> 12.0, 16.8, 14.2, 12.7, 14.…
    ## $ female                                    <dbl> 51.3, 51.1, 46.9, 46.3, 50.…
    ## $ white                                     <dbl> 78.5, 85.7, 48.0, 75.8, 92.…
    ## $ black                                     <dbl> 17.7, 9.4, 46.9, 22.0, 1.3,…
    ## $ native                                    <dbl> 0.4, 0.7, 0.4, 0.3, 0.5, 0.…
    ## $ asian                                     <dbl> 0.9, 0.7, 0.4, 0.1, 0.2, 0.…
    ## $ pac_isl                                   <dbl> NA, NA, NA, NA, NA, NA, 0.0…
    ## $ two_plus_races                            <dbl> 1.6, 1.5, 0.9, 0.9, 1.2, 0.…
    ## $ hispanic                                  <dbl> 2.4, 4.4, 5.1, 1.8, 8.1, 7.…
    ## $ white_not_hispanic                        <dbl> 77.2, 83.5, 46.8, 75.0, 88.…
    ## $ no_move_in_one_plus_year                  <dbl> 86.3, 83.0, 83.0, 90.5, 87.…
    ## $ foreign_born                              <dbl> 2.0, 3.6, 2.8, 0.7, 4.7, 1.…
    ## $ foreign_spoken_at_home                    <dbl> 3.7, 5.5, 4.7, 1.5, 7.2, 3.…
    ## $ hs_grad                                   <dbl> 85.3, 87.6, 71.9, 74.5, 74.…
    ## $ bachelors                                 <dbl> 21.7, 26.8, 13.5, 10.0, 12.…
    ## $ veterans                                  <dbl> 5817, 20396, 2327, 1883, 40…
    ## $ mean_work_travel                          <dbl> 25.1, 25.8, 23.8, 28.3, 33.…
    ## $ housing_units                             <dbl> 22135, 104061, 11829, 8981,…
    ## $ home_ownership                            <dbl> 77.5, 76.7, 68.0, 82.9, 82.…
    ## $ housing_multi_unit                        <dbl> 7.2, 22.6, 11.1, 6.6, 3.7, …
    ## $ median_val_owner_occupied                 <dbl> 133900, 177200, 88200, 8120…
    ## $ households                                <dbl> 19718, 69476, 9795, 7441, 2…
    ## $ persons_per_household                     <dbl> 2.70, 2.50, 2.52, 3.02, 2.7…
    ## $ per_capita_income                         <dbl> 24568, 26469, 15875, 19918,…
    ## $ median_household_income                   <dbl> 53255, 50147, 33219, 41770,…
    ## $ poverty                                   <dbl> 10.6, 12.2, 25.0, 12.6, 13.…
    ## $ private_nonfarm_establishments            <dbl> 877, 4812, 522, 318, 749, 1…
    ## $ private_nonfarm_employment                <dbl> 10628, 52233, 7990, 2927, 6…
    ## $ percent_change_private_nonfarm_employment <dbl> 16.6, 17.4, -27.0, -14.0, -…
    ## $ nonemployment_establishments              <dbl> 2971, 14175, 1527, 1192, 35…
    ## $ firms                                     <dbl> 4067, 19035, 1667, 1385, 44…
    ## $ black_owned_firms                         <dbl> 15.2, 2.7, NA, 14.9, NA, NA…
    ## $ native_owned_firms                        <dbl> NA, 0.4, NA, NA, NA, NA, NA…
    ## $ asian_owned_firms                         <dbl> 1.3, 1.0, NA, NA, NA, NA, 3…
    ## $ pac_isl_owned_firms                       <dbl> NA, NA, NA, NA, NA, NA, NA,…
    ## $ hispanic_owned_firms                      <dbl> 0.7, 1.3, NA, NA, NA, NA, N…
    ## $ women_owned_firms                         <dbl> 31.7, 27.3, 27.0, NA, 23.2,…
    ## $ manufacturer_shipments_2007               <dbl> NA, 1410273, NA, 0, 341544,…
    ## $ mercent_whole_sales_2007                  <dbl> NA, NA, NA, NA, NA, NA, 567…
    ## $ sales                                     <dbl> 598175, 2966489, 188337, 12…
    ## $ sales_per_capita                          <dbl> 12003, 17166, 6334, 5804, 5…
    ## $ accommodation_food_service                <dbl> 88157, 436955, NA, 10757, 2…
    ## $ building_permits                          <dbl> 191, 696, 10, 8, 18, 1, 3, …
    ## $ fed_spending                              <dbl> 331142, 1119082, 240308, 16…
    ## $ area                                      <dbl> 594.44, 1589.78, 884.88, 62…
    ## $ density                                   <dbl> 91.8, 114.6, 31.0, 36.8, 88…

``` r
str(countyComplete)
```

    ## 'data.frame':    3143 obs. of  53 variables:
    ##  $ state                                    : Factor w/ 51 levels "Alabama","Alaska",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ name                                     : Factor w/ 1877 levels "Abbeville County",..: 83 90 101 151 166 227 237 250 298 320 ...
    ##  $ FIPS                                     : num  1001 1003 1005 1007 1009 ...
    ##  $ pop2010                                  : num  54571 182265 27457 22915 57322 ...
    ##  $ pop2000                                  : num  43671 140415 29038 20826 51024 ...
    ##  $ age_under_5                              : num  6.6 6.1 6.2 6 6.3 6.8 6.5 6.1 5.7 5.3 ...
    ##  $ age_under_18                             : num  26.8 23 21.9 22.7 24.6 22.3 24.1 22.9 22.5 21.4 ...
    ##  $ age_over_65                              : num  12 16.8 14.2 12.7 14.7 13.5 16.7 14.3 16.7 17.9 ...
    ##  $ female                                   : num  51.3 51.1 46.9 46.3 50.5 45.8 53 51.8 52.2 50.4 ...
    ##  $ white                                    : num  78.5 85.7 48 75.8 92.6 23 54.4 74.9 58.8 92.7 ...
    ##  $ black                                    : num  17.7 9.4 46.9 22 1.3 70.2 43.4 20.6 38.7 4.6 ...
    ##  $ native                                   : num  0.4 0.7 0.4 0.3 0.5 0.2 0.3 0.5 0.2 0.5 ...
    ##  $ asian                                    : num  0.9 0.7 0.4 0.1 0.2 0.2 0.8 0.7 0.5 0.2 ...
    ##  $ pac_isl                                  : num  NA NA NA NA NA NA 0 0.1 0 0 ...
    ##  $ two_plus_races                           : num  1.6 1.5 0.9 0.9 1.2 0.8 0.8 1.7 1.1 1.5 ...
    ##  $ hispanic                                 : num  2.4 4.4 5.1 1.8 8.1 7.1 0.9 3.3 1.6 1.2 ...
    ##  $ white_not_hispanic                       : num  77.2 83.5 46.8 75 88.9 21.9 54.1 73.6 58.1 92.1 ...
    ##  $ no_move_in_one_plus_year                 : num  86.3 83 83 90.5 87.2 88.5 92.8 82.9 86.2 88.1 ...
    ##  $ foreign_born                             : num  2 3.6 2.8 0.7 4.7 1.1 1.1 2.5 0.9 0.5 ...
    ##  $ foreign_spoken_at_home                   : num  3.7 5.5 4.7 1.5 7.2 3.8 1.6 4.5 1.6 1.4 ...
    ##  $ hs_grad                                  : num  85.3 87.6 71.9 74.5 74.7 74.7 74.8 78.5 71.8 73.4 ...
    ##  $ bachelors                                : num  21.7 26.8 13.5 10 12.5 12 11 16.1 10.8 10.5 ...
    ##  $ veterans                                 : num  5817 20396 2327 1883 4072 ...
    ##  $ mean_work_travel                         : num  25.1 25.8 23.8 28.3 33.2 28.1 25.1 22.1 23.6 26.2 ...
    ##  $ housing_units                            : num  22135 104061 11829 8981 23887 ...
    ##  $ home_ownership                           : num  77.5 76.7 68 82.9 82 76.9 69 70.7 71.4 77.5 ...
    ##  $ housing_multi_unit                       : num  7.2 22.6 11.1 6.6 3.7 9.9 13.7 14.3 8.7 4.3 ...
    ##  $ median_val_owner_occupied                : num  133900 177200 88200 81200 113700 ...
    ##  $ households                               : num  19718 69476 9795 7441 20605 ...
    ##  $ persons_per_household                    : num  2.7 2.5 2.52 3.02 2.73 2.85 2.58 2.46 2.51 2.22 ...
    ##  $ per_capita_income                        : num  24568 26469 15875 19918 21070 ...
    ##  $ median_household_income                  : num  53255 50147 33219 41770 45549 ...
    ##  $ poverty                                  : num  10.6 12.2 25 12.6 13.4 25.3 25 19.5 20.3 17.6 ...
    ##  $ private_nonfarm_establishments           : num  877 4812 522 318 749 ...
    ##  $ private_nonfarm_employment               : num  10628 52233 7990 2927 6968 ...
    ##  $ percent_change_private_nonfarm_employment: num  16.6 17.4 -27 -14 -11.4 -18.5 2.1 -5.6 -45.8 5.4 ...
    ##  $ nonemployment_establishments             : num  2971 14175 1527 1192 3501 ...
    ##  $ firms                                    : num  4067 19035 1667 1385 4458 ...
    ##  $ black_owned_firms                        : num  15.2 2.7 NA 14.9 NA NA NA 7.2 NA NA ...
    ##  $ native_owned_firms                       : num  NA 0.4 NA NA NA NA NA NA NA NA ...
    ##  $ asian_owned_firms                        : num  1.3 1 NA NA NA NA 3.3 1.6 NA NA ...
    ##  $ pac_isl_owned_firms                      : num  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ hispanic_owned_firms                     : num  0.7 1.3 NA NA NA NA NA 0.5 NA NA ...
    ##  $ women_owned_firms                        : num  31.7 27.3 27 NA 23.2 38.8 NA 24.7 29.3 14.5 ...
    ##  $ manufacturer_shipments_2007              : num  NA 1410273 NA 0 341544 ...
    ##  $ mercent_whole_sales_2007                 : num  NA NA NA NA NA ...
    ##  $ sales                                    : num  598175 2966489 188337 124707 319700 ...
    ##  $ sales_per_capita                         : num  12003 17166 6334 5804 5622 ...
    ##  $ accommodation_food_service               : num  88157 436955 NA 10757 20941 ...
    ##  $ building_permits                         : num  191 696 10 8 18 1 3 107 10 6 ...
    ##  $ fed_spending                             : num  331142 1119082 240308 163201 294114 ...
    ##  $ area                                     : num  594 1590 885 623 645 ...
    ##  $ density                                  : num  91.8 114.6 31 36.8 88.9 ...

## Problem 2

Use lm() to create a model to predict median household income using 5
other variables. Do not include per capita income. Display a summary of
the model.

``` r
# Place your code here.

mod1 <- lm(median_household_income~poverty+bachelors+persons_per_household+median_val_owner_occupied+mean_work_travel, data=countyComplete)
summary(mod1)
```

    ## 
    ## Call:
    ## lm(formula = median_household_income ~ poverty + bachelors + 
    ##     persons_per_household + median_val_owner_occupied + mean_work_travel, 
    ##     data = countyComplete)
    ## 
    ## Residuals:
    ##    Min     1Q Median     3Q    Max 
    ## -21905  -2390   -183   2076  34176 
    ## 
    ## Coefficients:
    ##                             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)                1.387e+04  8.979e+02   15.45   <2e-16 ***
    ## poverty                   -1.056e+03  1.421e+01  -74.33   <2e-16 ***
    ## bachelors                  4.520e+02  1.364e+01   33.12   <2e-16 ***
    ## persons_per_household      1.230e+04  3.382e+02   36.38   <2e-16 ***
    ## median_val_owner_occupied  2.707e-02  1.368e-03   19.78   <2e-16 ***
    ## mean_work_travel           1.610e+02  1.557e+01   10.34   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 4406 on 3137 degrees of freedom
    ## Multiple R-squared:  0.8547, Adjusted R-squared:  0.8544 
    ## F-statistic:  3689 on 5 and 3137 DF,  p-value: < 2.2e-16

## Problem 3

Which 2 numbers in the summary output describe the overall performance
of the model. Use these two numbers in appropriate sentences to describe
how well your model performed.

Place your answer here.

This model has a residual standard error of 6271, and the adjusted
R-square is 0.7113 This shows that there is a postive correlation
between the five chosen variables and median household income.

## Problem 4

Examine the p-values for the individual coefficients of the model. Can
you reject the hypothesis that the true coefficient value is zero in
every case?

Place your answer here.

We can reject the hypothesis that the true coefficient value is zero,
which is the null hypothesis, because all the variables have the
smallest possilble p-values, 2e-16, showing that there is likely a
non-zero true coefficient value for each variable.

## Problem 5

Look at the signs of the coefficients. Do all of them have the signs
that you would expect? Note any exceptions.

Place your answer here.

The only coefficent that has a sign I did not expect was bachelors,
which is a positive I would not have thought that bachelors would have
such a high coefficient for median household income.

## Problem 6

Construct forecasts of median household income for three different
countys: Thurston County Washington, Los Angeles County California and
Fayette County Kentucky. Use the predict() function. Describe how the
forecasts compare with the actuals.

``` r
# Place your code here.
Thurston <- countyComplete %>%
  filter(name == "Thurston County" & state == "Washington")
predictThurs <- predict(mod1, newdata = Thurston)
predictThurs
```

    ##       1 
    ## 58283.8

``` r
Los_Angeles <- countyComplete %>%
  filter(name == "Los Angeles County" & state == "California")
predictLA <- predict(mod1, newdata = Los_Angeles)
predictLA
```

    ##       1 
    ## 65379.7

``` r
Fayette <- countyComplete %>%
  filter(name == "Fayette County" & state == "Kentucky")
predictFay <- predict(mod1, newdata = Fayette)
predictFay
```

    ##       1 
    ## 48822.7

``` r
#The actual medians
actualThurston <- countyComplete %>%
  filter(name == "Thurston County" & state == "Washington") %>%
  summarize(medT=median(median_household_income))
actualThurston
```

    ##    medT
    ## 1 60930

``` r
actualLos_Angeles <- countyComplete %>%
  filter(name == "Los Angeles County" & state == "California") %>%
  summarize(medLA=median(median_household_income))
actualLos_Angeles
```

    ##   medLA
    ## 1 55476

``` r
actualFayette <- countyComplete %>%
  filter(name == "Fayette County" & state == "Kentucky") %>%
  summarize(medF=median(median_household_income))
actualFayette
```

    ##    medF
    ## 1 47469

Put your verbal answer here.

The model predicts the median for Thurston to be 58283.8 , but is
actually 60930, the difference is very accurate and within the residual
standard error. Los Angeles is predicted to be 65379.7, but is acutally
55476, the difference is over the residual standard error. I believe the
model is so far of in its prediction for LA because LA has a much larger
population. Using variables that account for population may make the
results more accurate. Fayyete is predicted to be 48822.7, and is
actually 47469, the difference is fairly small and within the residual
standard error.
